package ru.aviasales.dal.model;

public enum CampaignSignatureEventType {
    MODERATOR_SIGNED,
    CLIENT_SIGNED,
    MODERATOR_SIGN_CONFIRMED,
    CLIENT_SIGN_CONFIRMED,
    DOCUMENT_FROZEN,
    SIGNATURE_COMPLETED,
    EDO_DOCUMENT_SENT,
    EDO_COUNTERSIGN_INITIATED
}
